# generated by datamodel-codegen:
#   filename:  spec.yaml
#   timestamp: 2026-02-18T18:14:15+00:00

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field, SecretStr, constr


class HealthCheckResponse(BaseModel):
    status: str = Field(..., description='Health status', example='ok')
    message: str = Field(
        ..., description='Additional information', example='Go to /docs to test login'
    )


class UserAuth(BaseModel):
    username: constr(min_length=1) = Field(..., description='Username for the account')
    password: SecretStr = Field(..., description='Password for the account')


class CookieObj(BaseModel):
    originalMaxAge: int | None = Field(
        None, description='Original max age in milliseconds'
    )
    expires: datetime | None = Field(None, description='Expiration date of the cookie')
    httpOnly: bool | None = Field(True, description='Whether the cookie is HTTP only')
    path: str | None = Field('/', description='Path for which the cookie is valid')


class UserIDObj(BaseModel):
    id: int = Field(..., description='User ID')


class Error(BaseModel):
    detail: str = Field(
        ..., description='Error message', example='Username already registered'
    )


class UserProfile(BaseModel):
    id: int = Field(..., description='User ID', example=1)
    username: str = Field(..., description='Username', example='john_doe')
    message: str = Field(..., description='Welcome message', example='Welcome back!')


class PassportObj(BaseModel):
    user: UserIDObj


class LoginResponse(BaseModel):
    cookie: CookieObj
    passport: PassportObj
